#define OP_CALL "__call"
#define OP_GET "__get"
#define OP_SET "__set"

#define OP_UN_PLUS "__pos"
#define OP_UN_MINUS "__neg"
#define OP_UN_CARET "__bnot"
#define OP_UN_LEN "__len"

#define OP_BIN_POWER "__pow"
#define OP_BIN_TIMES "__mul"
#define OP_BIN_IDIV "__idiv"
#define OP_BIN_FDIV "__div"
#define OP_BIN_MOD "__mod"
#define OP_BIN_MINUS "__sub"
#define OP_BIN_PLUS "__add"
#define OP_BIN_SHL "__bshl"
#define OP_BIN_SHR "__bshr"
#define OP_BIN_AMP "__band"
#define OP_BIN_AMPCARET "__bandnot"
#define OP_BIN_CARET "__bxor"
#define OP_BIN_BAR "__bor"
#define OP_BIN_TILDE "__concat"
#define OP_BIN_LT "__lt"
#define OP_BIN_GT "__gt"
#define OP_BIN_LE "__le"
#define OP_BIN_GE "__ge"
#define OP_BIN_EQ "__eq"
#define OP_BIN_NE "__ne"
#define  OP_BIN_MATCH "__match"
#define OP_BIN_NOMATCH "__nomatch"


