#!/bin/sh

printf "====================\n"
printf "Building...\n"
cmake --build .
# make YASL
EXEC_BUILD_OUTPUT=$?
# make YASLTEST
TEST_BUILD_OUTPUT=$?
if [ $EXEC_BUILD_OUTPUT$TEST_BUILD_OUTPUT != 00 ]; then
  printf "Build failed\n"
  exit 1
fi
printf "Build successful\n\n"

printf "========================================\n"
printf "Running compiler tests...\n"
./yasltest
C_TESTS_OUTPUT=$?
printf "C Unit tests exited with code $C_TESTS_OUTPUT\n\n"

printf "========================================\n"
printf "Running VM tests...\n"
( cd test ; perl vmtest.pl )
VM_TESTS_OUTPUT=$?
printf "VM tests exited with code $VM_TESTS_OUTPUT\n\n"

printf "========================================\n"
printf "Running CLI tests...\n"
( cd test ; perl clitest.pl )
CLI_TESTS_OUTPUT=$?
printf "CLI tests exited with code $CLI_TESTS_OUTPUT\n\n"

printf "========================================\n"
printf "Running script tests...\n"
( cd test ; perl filetest.pl )
FILE_TESTS_OUTPUT=$?
printf "Script tests exited with code $FILE_TESTS_OUTPUT\n\n"

MEM_TESTS_OUTPUT=0
if [ "$1" != '-m' ]; then
  printf "========================================\n"
  printf "Running memory tests...\n"
  ( cd test ; perl memtest.pl )
  MEM_TESTS_OUTPUT=$?
  printf "Memory tests exited with code $MEM_TESTS_OUTPUT\n\n"
fi

printf "========================================\n"
[ $C_TESTS_OUTPUT$VM_TESTS_OUTPUT$CLI_TESTS_OUTPUT$MEM_TESTS_OUTPUT$FILE_TESTS_OUTPUT = 00000 ]
TESTS_EXIT=$?
printf "Tests exited with code $TESTS_EXIT\n"

exit $TESTS_EXIT
