#ifndef TEST_UNITTESTS_TESTCOMPILER_COMPREHENSIONTEST_H_
#define TEST_UNITTESTS_TESTCOMPILER_COMPREHENSIONTEST_H_

#include "yats.h"

TEST(comprehensiontest);

#endif  // TEST_UNITTESTS_TESTCOMPILER_COMPREHENSIONTEST_H_