#ifndef TEST_UNITTESTS_TESTCOMPILER_SYNTAXERRORTEST_H_
#define TEST_UNITTESTS_TESTCOMPILER_SYNTAXERRORTEST_H_

#include "yats.h"

TEST(syntaxerrortest);

#endif  // TEST_UNITTESTS_TESTCOMPILER_SYNTAXERRORTEST_H_