static const char *assert_errors[] = {
  "test/errors/assert/else.yasl",
  "test/errors/assert/table.yasl",
  "test/errors/assert/assert_return.yasl",
  "test/errors/assert/for.yasl",
  "test/errors/assert/assert_long.yasl",
  "test/errors/assert/elseif.yasl",
  "test/errors/assert/if.yasl",
  "test/errors/assert/foreach.yasl",
  "test/errors/assert/while.yasl",
  "test/errors/assert/nested_fn_call.yasl",
  "test/errors/assert/undef.yasl",
  "test/errors/assert/assert_in_fn.yasl",
  "test/errors/assert/fn_call.yasl",
  "test/errors/assert/assert.yasl",
};
