static const char *value_errors[] = {
  "test/errors/value/io/open1.yasl",
  "test/errors/value/io/open2.yasl",
  "test/errors/value/io/open3.yasl",
  "test/errors/value/io/read1.yasl",
  "test/errors/value/io/read2.yasl",
  "test/errors/value/list/__get.yasl",
  "test/errors/value/list/pop.yasl",
  "test/errors/value/list/__set.yasl",
  "test/errors/value/list/sort.yasl",
  "test/errors/value/str/__get.yasl",
  "test/errors/value/str/replace.yasl",
  "test/errors/value/str/rep.yasl",
  "test/errors/value/str/split.yasl",
};
